#! /bin/sh
# bspc rule -r "*"

# picom --config /home/brian/.config/picom/picom.conf & # --experimental-backends &
# feh --bg-fill /home/brian/Pictures/nord_mountains.png &
feh --bg-fill /home/brian/Pictures/leaves.jpg &
# feh --bg-fill /home/brian/Pictures/gruvbox_braille.png &
bst -e btop &

#sxhkd keybindings (unneccessary since it is called from ~/.xinitrc)
# pgrep -x sxhkd > /dev/null || sxhkd -c /home/brian/.config/sxhkd/sxhkdrc &
# Monitor(s)
# bspc monitor -d I II III IV V VI VII VIII IX X
# Desktop
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
# Laptop
# bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10

#Global Settings
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "#44444"
# bspc config active_border_color "#64a098"
bspc config active_border_color "#2c77ac"
# bspc config active_border_color "#a9b926"
# bspc config focused_border_color "#64a098"
bspc config focused_border_color "#2c77ac"
# bspc config focused_border_color "#a9b926"
# bspc config presel_feedback_color "#64a098"
bspc config presel_feedback_color "#2c77ac"
# bspc config presel_feedback_color "#a9b926"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Enable Gaps
bspc config top_padding 3
bspc config bottom_padding 3
bspc config left_padding 3
bspc config right_padding 3
bspc config border_width 1
bspc config window_gap 5

# bspc rule -a pavucontrol state=floating rectangle=480x270+1440+810 sticky=on layer=above
# bspc rule -a lxappearance state=floating rectangle=480x270+1440+810 sticky=on layer=above
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
