[[Accounts]]
Name = 'z3rOR0ne'
Server = 'https://mastodon.social'
ClientID = 'W5-vc3KFNdN9Yi4b-K1zYFmer4ckv82mWSI-RWGGGKc'
ClientSecret = 'aa8fmX_X8jb6RMVoS-oafplYThqyBVmUB17NdYLSHL8'
AccessToken = 'zyao-A-Au6QdsirYQkjyJ48EKbUUMvjnBmBPEbkotN0'
