#!/bin/bash

while [ true ] ; do
	PWRLVL=$(cat /sys/class/power_supply/BAT1/capacity)
        if [ $PWRLVL -eq 15 ] ; then
            exec notify-send "Battery is at 15%!!";
            break;
        else
            sleep 15s;
        fi
done
