#!/bin/bash

# simple script that prints out current time in hours:mins format
# to be utilized in a bash version of calcurse_reminder.py

hours=$(date +"%T" | awk -F ":" '{print $1}')
mins=$(date +"%T" | awk -F ":" '{print $2}')

currenttime="${hours}:${mins}"

echo "${currenttime}"
