#!/usr/bin/env bash

if [[ "$#" -eq 0 ]]; then
    $BROWSER "https://commons.wikimedia.org/?useskin=vector"
else
    search=""
    for i in "$@"; do
    search="+${i}"
    done
    search="${search:1}"
$BROWSER "https://commons.wikimedia.org/w/index.php?search=${search}&title=Special%3AMediaSearch&fulltext=Search&useskin=vector"
fi
