#!/bin/bash

# Error handling
set -e

# For styling/colorizing output
txtbld=$(tput bold)
txtred=${txtbld}$(tput setaf 1)
txtwhite=${txtbld}$(tput setaf 7)

# Dependency check
function dependencycheck()
{
    numdependencies="$#"
    dependencies=("$@")
    missingdependencies=0

    for ((i = 0; i < numdependencies; i++)) ; do
        if ! command -v "${dependencies[$i]}" &> /dev/null ; then
            echo "${txtred}dependency not met: ${dependencies[$i]}${txtwhite}"
            missingdependencies=$((missingdependencies+1))
        fi
    done

    if [ $missingdependencies -gt 0 ] ; then
        echo "${txtred}Please install needed dependencies${txtwhite}"
        exit 1
    fi
}

# invoke function comment out if sourced
dependencycheck "$@"

# Barebones version without tput (for being sourced):
# function dependencycheck()
# {
    # numdependencies="$#"
    # dependencies=("$@")
    # missingdependencies=0

    # for ((i = 0; i < numdependencies; i++)) ; do
        # if ! command -v "${dependencies[$i]}" &> /dev/null ; then
            # echo "dependency not met: ${dependencies[$i]}"
            # missingdependencies=$((missingdependencies+1))
        # fi
    # done

    # if [ $missingdependencies -gt 0 ] ; then
        # echo "Please install needed dependencies"
        # exit 1
    # fi
# }
