#!/usr/bin/env bash

 v4l2-ctl -d /dev/video0 --set-ctrl=brightness=120
 v4l2-ctl -d /dev/video0 --set-ctrl=saturation=170
 v4l2-ctl -d /dev/video0 --set-ctrl=contrast=128
 v4l2-ctl -d /dev/video0 --set-ctrl=sharpness=150
v4l2-ctl -d /dev/video0 --set-ctrl=zoom_absolute=300
