#!/usr/bin/env bash
# Utilize in conjunction with espanso, call ;html5
cat <<EOM
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>html page</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/x-icon" href="favicon.png">
        <link rel="stylesheet" type="text/css" href="css/style.css">
    </head>
    <body>
    
    </body>
    <script src="./index.js" default></script>
</html>
EOM
