#!/usr/bin/env bash
# Utilize in conjunction with espanso, call ;kcss
cat <<EOM
*,
*::before,
*::after {
  box-sizing: border-box;
}

:root {
  color-scheme: light dark;
}

body {
  font-family: system-ui;
  font-size: 1.125rem;
  line-height: 1.5;
}

main {
  width: min(70ch, 100% - 4rem);
  margin-inline: auto;
}

img,
svg,
video {
  max-width: 100%;
  display: block;
}

input,
textarea {
    min-width: 0;
}

/* background image specific, courtesy wittcode*/
/*
body {
  background-image: url("background_image.png");
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
  background-size: cover;
}

h1,
h2,
h3,
h4,
h5,
h6 {
    text-wrap: balance;
}

p,
li,
figcaption {
    text-wrap: pretty;
    max-width: 65ch;
}

header,
footer,
main,
section,
article {
    container-type: inline-size;
}
*/
EOM
