#!/bin/bash

source "${HOME}"/.n_hidden
lastarg=("${@: -1}")

search=""
for ARG in "${@}" ; do
    if [[ $ARG == "${lastarg[1]}" ]] ; then
        search+="${ARG}"
    else
        search+="${ARG}+"
    fi
done

$BROWSER "${N1}"/video/search?search="${search}" &
