#!/usr/bin/env bash
# Utilize in conjunction with espanso, call ;pug5
cat <<EOM
doctype html
html(lang = "en")
    head
        title html page
        meta(charset="utf-8")
        meta(name="viewport" content="width=device-width, initial-scale=1")
        meta(name="robots" content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large")
        meta(name="description" content="")
        link(rel="icon" type="image/x-icon" href="favicon.png")
        link(rel="stylesheet" type="text/css" href="css/style.css")
        link(rel="preload" href="css/style.css" as="style" onload="this.onload=null;this.rel='stylesheet'")
        noscript
            link(rel="stylesheet" href="css/style.css")
    body
        main
            article
                h1 My Heading
                    p Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        script(src="./index.js" default defer)
EOM