#!/usr/bin/env bash
# Utilize in conjunction with espanso, call ;pug5
cat <<EOM
doctype html
html(lang = "en")
    head
        title html page
        meta(charset="utf-8")
        meta(name="viewport" content="width=device-width, initial-scale=1")
        meta(name="robots" content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large")
        meta(name="description" content="")
        link(rel="icon" type="image/x-icon" href="favicon.png")
        link(rel="stylesheet" type="text/css" href="css/style.css")
    body
        script(src="./index.js" default)
EOM