#!/bin/bash
# A simple bookmarking script used in conjunction with rdir
# to save a directory for easy navigation later

# save our current working directory
sdir=$(pwd)
# allow overwriting of sdrc
set +o noclobber

# define and create .sdrc file
sdrc="$HOME/".sdrc
if [[ ! -f "$sdir" ]] ; then
    /usr/bin/touch "$sdir"
fi

echo 'export sdir='"$sdir" > "$sdrc"
# immediately source ~/.sdrc
source "$sdrc"
