#!/bin/bash
# used with espanso :rdr and :rdd command
# A simple bookmarking script used in conjunction with rdir
# to save a directory for easy navigation later

# save our current working directory
sdir=$(pwd)
# allow overwriting of sdrc
set +o noclobber

# define and create .sdrc file
sdrc="$HOME/".sdrc
if [[ ! -f "$sdir" ]] ; then
    /usr/bin/touch "$sdir"
fi

if [[ $# -eq 1 ]] ; then
    sdoc="$1"
    sdline="0"
else
    sdoc=""
fi

if [[ $# -eq 2 ]] ; then
    sdoc="$1"
    sdline="$2"
fi

echo 'export sdir='"$sdir" > "$sdrc"
echo 'export sdoc='"$sdoc" >> "$sdrc"
echo 'export sdline='"$sdline" >> "$sdrc"
