#!/bin/bash

# git blame script showing how many commits each author has made in total
# https://stackoverflow.com/questions/4589731/git-blame-commit-statistics
git ls-tree -r -z --name-only HEAD -- $1 | sed 's/^/.\//' | xargs -0 -n1 git blame \
 --line-porcelain HEAD |grep -ae "^author "|sort|uniq -c|sort -nr
