#!/usr/bin/env bash

main() {
    if [[ $(/usr/bin/id -u) -ne 0 ]]; then
        echo "This script must be run as root!"
        exit 1
    else
        set +o noclobber
        sv stop wireguard
        cat <<EOF >/etc/resolv.conf
nameserver ::1
nameserver 127.0.0.1
options trust-ad
EOF
        chattr +i /etc/resolv.conf
        docker container start pihole-unbound
        sv restart NetworkManager
        set -o noclobber
    fi
}

main
