#!/usr/bin/env bash

main() {
    if [[ $(/usr/bin/id -u) -ne 0 ]]; then
        echo "This script must be run as root!"
        exit 1
    else
        docker container stop pihole-unbound
        chattr -i /etc/resolv.conf 2>/dev/null
        sv restart NetworkManager
        sv start wireguard
    fi
}

main
